### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/pokeruby-kr#9]
- [ ] 포켓내비: 트레이너 아이 목록 레이아웃
![pokeruby_modern_02](https://github.com/poketony/pokeruby-kr/assets/39587773/05c31254-d30a-41d9-a081-af8d156f0c2a)![pokeruby_jp_01](https://github.com/poketony/pokeruby-kr/assets/39587773/7e9a8d0c-bd27-4cfb-a07f-af2ad319da4a)

- [ ] PC 좌측 레이아웃
![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/c4132666-11e2-4793-8301-94f5ddb7fba0)![pokeruby_jp_01](https://github.com/poketony/pokeruby-kr/assets/39587773/ce583045-2f8d-49f4-bc79-715572d70139)

**Comment by koipkoi** [comment]
- [ ] 닉네임 & 성별 버그
![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/9d3269d9-26c1-4cb2-bf53-a304be2db5a9)

**Comment by poketony** [comment]
- [ ] 시계 선택지 그래픽 한글화하기
![pokesapphire-0](https://github.com/koipkoi/pokeruby-kr/assets/57011422/d39f3803-b855-4fe2-99e5-ddde4db29b84)![pokesapphire-1](https://github.com/koipkoi/pokeruby-kr/assets/57011422/6b554786-c0b8-4b05-9724-e783cd0f7ea3)

**Comment by koipkoi** [comment]
@
